all:
  vars:
    ansible_user: hoangan1606
    ansible_ssh_private_key_file: /home/hoangan1606/.ssh/ansible_ed25519
    ansible_python_interpreter: /usr/bin/python3
  children:
    management:
      hosts:
        management01:
          ansible_host: 192.168.122.149
    webservers:
      hosts:
        webserver01:
          ansible_host: 192.168.122.26
    databases:
      hosts:
        database01:
          ansible_host: 192.168.122.223
    monitored_nodes:
      children:
        management:
        webservers:
        databases:
    node_exporters:
      children:
        webservers:
        databases:

