from datetime import datetime

class ReportManager:

    def __init__(self,monitor):
        self.monitor = monitor

    def generate(self):
        now = datetime.now()
        filename = now.strftime(
            "reports/server_report_%Y%m%d_%H%M%S.txt"
        )
        report = f""""
=========================================
              SERVER REPORT
=========================================

Hostname:
{self.monitor.hostname()}

Uptime:
{self.monitor.uptime()}

CPU:
{self.monitor.memory()}

Memory:
{self.monitor.memory()}

Disk:
{self.monitor.memory()}

Nginx:
{self.monitor.nginx()}

IP Address:
{self.monitor.ip_address()}

Gateway:
{self.monitor.gateway()}

=========================================
      Generated by Server Monitor
=========================================
"""
        with open(filename, "w") as file:
            file.write(report)
        print("\nReport Saved:")
        print(filename)

