name: Server Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker Image
      run: |
        test -f k8s/deployment.yaml
        test -f k8s/service.yaml
    - name: CI Success
      run: echo "Build Success!"

